server:
  port: 8081
spring:
  application.name: ututor2back
  datasource:
    url: jdbc:postgresql://localhost:5432/ututor2
    username: labaj
    password: test123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false
  flyway:
    locations: classpath:db/migration/postgres

